name: Continuous Integration
on:
  push:
    branches:
      - master
      - jenk
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java version: '17'
          distribution: 'zulu'
      - name: Show Java version
        run: 'java-version'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: jenk

      - name: Show directory
        run: 'pwd'

      - name: List files
        run: 'ls -al'
                
      - name: Install Dependencies
        run: 'mvn compile'

      - name: Build application
        run: 'mvn packege -DskipTests'

      - name: Test applicaation
        run: 'mvn test'

